### ISSUE TITLE
示例数据

### ISSUE THREAD

**Issue by 464hee** [fuscc-deep-path/sc_MTOP#1]
你好，关于F3代码的示例数据，能否提供参考一下呢？   
 fun3('./data_example/COWH/COWH.json',
         './data_example/COWH/COWH.ndpi',
         './data_example',
         xml_path=None)

**Comment by 464hee** [comment]
@CDPDisk

**Comment by CDPDisk** [comment]
抱歉回复比较迟。由于和医院方面的合作要求一些数据暂时无法公开，目前正在尝试提供体积较小的demo数据

**Comment by 464hee** [comment]
没关系，我现在想知道关于提取到的特征的解释有吗？就是想知道每个特征背后代表哪些统计意义

**Comment by CDPDisk** [comment]
目前论文正在投稿，因此与疾病相关上的意义无法给出详细解释，欢迎关注后续论文的发表情况。数学上的意义和定义公式则可以根据特征名和调用的函数去相应包的文档里查找。
