### ISSUE TITLE
Can you provide the code for leiden_clusters

### ISSUE THREAD

**Issue by 464hee** [fuscc-deep-path/sc_MTOP#4]
Of the 60 features generated for each cell type based on sc_MTOP, it looks like there are a large number of cells with NAN values. @afrendeiro @yjcyxky @CDPDisk

**Comment by CDPDisk** [comment]
In our analysis, anomalies primarily manifest in features related to the graph, with three main scenarios identified:

1. Empty values in edge length features (e.g., minEdgeLength, meanEdgeLength):
**Cause:** The cell represents an isolated node with no corresponding edges.
**Resolution:** Set the values to 100 (i.e., the maximum length between two connected nodes).
2. Empty values in some graph features (e.g., clustering_coefficient, closeness):
**Cause:** Nodes in a connected graph have too few neighbors, making feature computation impossible.
**Resolution:** Fill missing values with 0.
3. Inf values in the betweenness feature of a few nodes:
**Cause:** In large subgraphs, a few nodes near the center may result in betweenness exceeding the variable range.
**Resolution:** During analysis, exclude these nodes.

After addressing these issues, we transformed the feature data into the AnnData type from the scanpy or anndata package and utilized `scanpy.tl.leiden` for clustering. You can refer to scanpy's [documentation](https://scanpy.readthedocs.io/en/stable/generated/scanpy.tl.leiden.html) for guidance on this step.

If your data exhibits a significant number of unreasonable anomalies, consider modifying the graph construction methodology. Additionally, excessive variance in feature values during clustering may impact results, consider implementing preprocessing techniques such as log transformation and normalization.

**Comment by 464hee** [comment]
Thank you for your reply, it was clearly explained
